import dog from "../images/cards/dog.jpeg";
import cat from "../images/cards/cat.jpeg";
import goldfish from "../images/cards/goldfish.jpeg";
import sheep from "../images/cards/sheep.jpeg";
import weevil from "../images/cards/weevil.jpeg";
import snake from "../images/cards/snake.jpeg";
import elephant from "../images/cards/elephant.jpeg";
import whale from "../images/cards/whale.jpeg";
import lion from "../images/cards/lion.jpeg";
import mongoose from "../images/cards/mongoose.jpeg";
import parrot from "../images/cards/parrot.jpeg";
import toad from "../images/cards/toad.jpeg";
import giraffe from "../images/cards/giraffe.jpeg";
import owl from "../images/cards/owl.jpeg";
import robin from "../images/cards/robin.jpeg";
import badger from "../images/cards/badger.jpeg";
import baboon from "../images/cards/baboon.jpeg";
import ladybird from "../images/cards/ladybird.jpeg";
import stagbeetle from "../images/cards/stagbeetle.jpeg";
import trex from "../images/cards/trex.jpeg";

const cards = [
  {
    name: "Dog",
    aka: "Best friend",
    cool: 6,
    largeness: 5,
    handsome: 10,
    alignment: "Lawful Good",
    photo: dog,
    photographer: "Karsten Winegeart",
    link: "https://unsplash.com/@karsten116",
  },
  {
    name: "Cat",
    aka: "Tiddles",
    cool: 10,
    largeness: 4,
    handsome: 8,
    alignment: "Lawful Evil",
    photo: cat,
    photographer: "Manja Vitolic",
    link: "https://unsplash.com/@madhatterzone",
  },
  {
    name: "Goldfish",
    aka: "Flipper",
    cool: 3,
    largeness: 2,
    handsome: 7,
    alignment: "True Neutral",
    photo: goldfish,
    photographer: "pouria oskuie",
    link: "https://unsplash.com/@pouriaoskuie",
  },
  {
    name: "Sheep",
    aka: "Sheeple",
    cool: 2,
    largeness: 5,
    handsome: 5,
    alignment: "Chaotic Neutral",
    photo: sheep,
    photographer: "Sam Carter",
    link: "https://unsplash.com/@samdc",
  },
  {
    name: "Weevil",
    aka: "Tiny lad",
    cool: 1,
    largeness: 1,
    handsome: 1,
    alignment: "Chaotic Weevil",
    photo: weevil,
    photographer: "Dominik Scythe",
    link: "https://unsplash.com/@drscythe",
  },
  {
    name: "Snake",
    aka: "Long lad",
    cool: 8,
    largeness: 3,
    handsome: 7,
    alignment: "Lawful Evil",
    photo: snake,
    photographer: "Timothy Dykes",
    link: "https://unsplash.com/@timothycdykes",
  },
  {
    name: "Elephant",
    aka: "Leg-face",
    cool: 7,
    largeness: 8,
    handsome: 7,
    alignment: "Chaotic Good",
    photo: elephant,
    photographer: "Nam Anh",
    link: "https://unsplash.com/@bepnamanh",
  },
  {
    name: "Whale",
    aka: "Willy",
    cool: 8,
    largeness: 10,
    handsome: 5,
    alignment: "Lawful Neutral",
    photo: whale,
    photographer: "Todd Cravens",
    link: "https://unsplash.com/@toddcravens",
  },
  {
    name: "Lion",
    aka: "The King",
    cool: 8,
    largeness: 6,
    handsome: 10,
    alignment: "Lawful Neutral",
    photo: lion,
    photographer: "Francesco De Tommaso",
    link: "https://unsplash.com/@detpho",
  },
  {
    name: "Mongoose",
    aka: "Not a kind of goose",
    cool: 8,
    largeness: 4,
    handsome: 10,
    alignment: "Chaotic Good",
    photo: mongoose,
    photographer: "Ilyas Aliev",
    link: "https://unsplash.com/@i14",
  },
  {
    name: "Parrot",
    aka: "Pretty boy",
    cool: 7,
    largeness: 3,
    handsome: 10,
    alignment: "Neutral Good",
    photo: parrot,
    photographer: "Aaron Katz",
    link: "https://unsplash.com/@pendraggon87",
  },
  {
    name: "Toad",
    aka: "Warty",
    cool: 5,
    largeness: 2,
    handsome: 4,
    alignment: "Chaotic Neutral",
    photo: toad,
    photographer: "Jaunathan Gagnon",
    link: "https://unsplash.com/@jaunathang",
  },
  {
    name: "Giraffe",
    aka: "Lanky",
    cool: 7,
    largeness: 9,
    handsome: 6,
    alignment: "Neutral Good",
    photo: giraffe,
    photographer: "howling red",
    link: "https://unsplash.com/@howlingred70",
  },
  {
    name: "Owl",
    aka: "Hooter",
    cool: 8,
    largeness: 3,
    handsome: 10,
    alignment: "Lawful Good",
    photo: owl,
    photographer: "Dominik VO",
    link: "https://unsplash.com/@derobi",
  },
  {
    name: "Robin",
    aka: "Tweeter",
    cool: 6,
    largeness: 1,
    handsome: 10,
    alignment: "Chaotic Evil",
    photo: robin,
    photographer: "Chris",
    link: "https://unsplash.com/@chris23",
  },
  {
    name: "Badger",
    aka: "Stripy Tough Guy",
    cool: 7,
    largeness: 4,
    handsome: 7,
    alignment: "Chaotic Evil",
    photo: badger,
    photographer: "Vincent van Zalinge",
    link: "https://unsplash.com/@vincentvanzalinge",
  },
  {
    name: "Baboon",
    aka: "Red butt",
    cool: 8,
    largeness: 5,
    handsome: 8,
    alignment: "Chaotic Neutral",
    photo: baboon,
    photographer: "Max van den Oetelaar",
    link: "https://unsplash.com/@maxvdo",
  },
  {
    name: "Ladybird",
    aka: "Spotty",
    cool: 3,
    largeness: 1,
    handsome: 10,
    alignment: "Chaotic Good",
    photo: ladybird,
    photographer: "Vincent van Zalinge",
    link: "https://unsplash.com/@vincentvanzalinge",
  },
  {
    name: "Stag Beetle",
    aka: "Small fry",
    cool: 7,
    largeness: 1,
    handsome: 5,
    alignment: "Neutral Evil",
    photo: stagbeetle,
    photographer: "Krzysztof Niewolny",
    link: "https://unsplash.com/@epan5",
  },
  {
    name: "T-Rex",
    aka: "Wuh-oh",
    cool: 10,
    largeness: 10,
    handsome: 5,
    alignment: "Chaotic Neutral",
    photo: trex,
    photographer: "Umanoide",
    link: "https://unsplash.com/@umanoide",
  },
];

export { cards };
