import dog from "../images/cards/dog.jpeg";
import cat from "../images/cards/cat.jpeg";
import goldfish from "../images/cards/goldfish.jpeg";
import sheep from "../images/cards/sheep.jpeg";
import rabbit from "../images/cards/rabbit.jpeg";
import pig from "../images/cards/pig.jpeg";
import weevil from "../images/cards/weevil.jpeg";
import snake from "../images/cards/snake.jpeg";
import elephant from "../images/cards/elephant.jpeg";
import whale from "../images/cards/whale.jpeg";
import piranha from "../images/cards/piranha.jpeg";
import lion from "../images/cards/lion.jpeg";
import tiger from "../images/cards/tiger.jpeg";
import mongoose from "../images/cards/mongoose.jpeg";
import parrot from "../images/cards/parrot.jpeg";
import flamingo from "../images/cards/flamingo.jpeg";
import toad from "../images/cards/toad.jpeg";
import giraffe from "../images/cards/giraffe.jpeg";
import owl from "../images/cards/owl.jpeg";
import robin from "../images/cards/robin.jpeg";
import swan from "../images/cards/swan.jpeg";
import pigeon from "../images/cards/pigeon.jpeg";
import bee from "../images/cards/bee.jpeg";
import badger from "../images/cards/badger.jpeg";
import baboon from "../images/cards/baboon.jpeg";
import kangaroo from "../images/cards/kangaroo.jpeg";
import ladybird from "../images/cards/ladybird.jpeg";
import monkey from "../images/cards/monkey.jpeg";
import stagbeetle from "../images/cards/stagbeetle.jpeg";
import trex from "../images/cards/trex.jpeg";

const cards = [
  {
    name: "Dog",
    aka: "Best friend",
    cool: 6,
    largeness: 5,
    handsome: 10,
    alignment: "Lawful Good",
    photo: dog,
    photographer: "Karsten Winegeart",
    link: "https://unsplash.com/@karsten116",
  },
  {
    name: "Cat",
    aka: "Tiddles",
    cool: 10,
    largeness: 4,
    handsome: 8,
    alignment: "Lawful Evil",
    photo: cat,
    photographer: "Manja Vitolic",
    link: "https://unsplash.com/@madhatterzone",
  },
  {
    name: "Goldfish",
    aka: "Flipper",
    cool: 3,
    largeness: 2,
    handsome: 7,
    alignment: "True Neutral",
    photo: goldfish,
    photographer: "pouria oskuie",
    link: "https://unsplash.com/@pouriaoskuie",
  },
  {
    name: "Sheep",
    aka: "Sheeple",
    cool: 2,
    largeness: 5,
    handsome: 5,
    alignment: "Chaotic Neutral",
    photo: sheep,
    photographer: "Sam Carter",
    link: "https://unsplash.com/@samdc",
  },
  {
    name: "Rabbit",
    aka: "Thumper",
    cool: 6,
    largeness: 3,
    handsome: 9,
    alignment: "True Neutral",
    photo: rabbit,
    photographer: "Gavin Allanwood",
    link: "https://unsplash.com/@gavla",
  },
  {
    name: "Piglet",
    aka: "Handsome chap",
    cool: 8,
    largeness: 4,
    handsome: 10,
    alignment: "Lawful Good",
    photo: pig,
    photographer: "Forest Simon",
    link: "https://unsplash.com/@forest_ms",
  },
  {
    name: "Weevil",
    aka: "Tiny lad",
    cool: 1,
    largeness: 1,
    handsome: 1,
    alignment: "Chaotic Weevil",
    photo: weevil,
    photographer: "Dominik Scythe",
    link: "https://unsplash.com/@drscythe",
  },
  {
    name: "Snake",
    aka: "Long lad",
    cool: 8,
    largeness: 3,
    handsome: 7,
    alignment: "Lawful Evil",
    photo: snake,
    photographer: "Timothy Dykes",
    link: "https://unsplash.com/@timothycdykes",
  },
  {
    name: "Elephant",
    aka: "Leg-face",
    cool: 7,
    largeness: 8,
    handsome: 7,
    alignment: "Chaotic Good",
    photo: elephant,
    photographer: "Nam Anh",
    link: "https://unsplash.com/@bepnamanh",
  },
  {
    name: "Whale",
    aka: "Willy",
    cool: 8,
    largeness: 10,
    handsome: 5,
    alignment: "Lawful Neutral",
    photo: whale,
    photographer: "Todd Cravens",
    link: "https://unsplash.com/@toddcravens",
  },
  {
    name: "Piranha",
    aka: "Lil' bitey",
    cool: 9,
    largeness: 2,
    handsome: 5,
    alignment: "Chaotic Neutral",
    photo: piranha,
    photographer: "Anton Darius",
    link: "https://unsplash.com/@thesollers",
  },
  {
    name: "Lion",
    aka: "The King",
    cool: 8,
    largeness: 7,
    handsome: 10,
    alignment: "Lawful Neutral",
    photo: lion,
    photographer: "Francesco De Tommaso",
    link: "https://unsplash.com/@detpho",
  },
  {
    name: "Tiger",
    aka: "The Boss",
    cool: 9,
    largeness: 7,
    handsome: 9,
    alignment: "Lawful Neutral",
    photo: tiger,
    photographer: "A G",
    link: "https://unsplash.com/@agord70345203222008",
  },
  {
    name: "Mongoose",
    aka: "Not a kind of goose",
    cool: 8,
    largeness: 4,
    handsome: 10,
    alignment: "Chaotic Good",
    photo: mongoose,
    photographer: "Ilyas Aliev",
    link: "https://unsplash.com/@i14",
  },
  {
    name: "Parrot",
    aka: "Pretty boy",
    cool: 7,
    largeness: 3,
    handsome: 10,
    alignment: "Neutral Good",
    photo: parrot,
    photographer: "Aaron Katz",
    link: "https://unsplash.com/@pendraggon87",
  },
  {
    name: "Flamingo",
    aka: "Pinky",
    cool: 8,
    largeness: 5,
    handsome: 9,
    alignment: "Lawful Neutral",
    photo: flamingo,
    photographer: "Chris Stenger",
    link: "https://unsplash.com/@chrisstenger",
  },
  {
    name: "Toad",
    aka: "Warty",
    cool: 5,
    largeness: 2,
    handsome: 4,
    alignment: "Chaotic Neutral",
    photo: toad,
    photographer: "Jaunathan Gagnon",
    link: "https://unsplash.com/@jaunathang",
  },
  {
    name: "Giraffe",
    aka: "Lanky",
    cool: 7,
    largeness: 9,
    handsome: 6,
    alignment: "Neutral Good",
    photo: giraffe,
    photographer: "howling red",
    link: "https://unsplash.com/@howlingred70",
  },
  {
    name: "Owl",
    aka: "Hooter",
    cool: 8,
    largeness: 3,
    handsome: 10,
    alignment: "Lawful Good",
    photo: owl,
    photographer: "Dominik VO",
    link: "https://unsplash.com/@derobi",
  },
  {
    name: "Robin",
    aka: "Tweeter",
    cool: 6,
    largeness: 2,
    handsome: 10,
    alignment: "Chaotic Evil",
    photo: robin,
    photographer: "Chris",
    link: "https://unsplash.com/@chris23",
  },
  {
    name: "Swan",
    aka: "Graceful but deadly",
    cool: 8,
    largeness: 5,
    handsome: 10,
    alignment: "Neutral Evil",
    photo: swan,
    photographer: "Erik van Dijk",
    link: "https://unsplash.com/@erikvandijk",
  },
  {
    name: "Pigeon",
    aka: "Nice dude, bad PR",
    cool: 7,
    largeness: 3,
    handsome: 8,
    alignment: "Chaotic Neutral",
    photo: pigeon,
    photographer: "sanjiv nayak",
    link: "https://unsplash.com/@sanjiv222",
  },
  {
    name: "Bee",
    aka: "Buzzing friend",
    cool: 8,
    largeness: 1,
    handsome: 6,
    alignment: "Chaotic Good",
    photo: bee,
    photographer: "Dmitry Grigoriev",
    link: "https://unsplash.com/@at8eqeq3",
  },
  {
    name: "Badger",
    aka: "Stripy tough guy",
    cool: 7,
    largeness: 4,
    handsome: 7,
    alignment: "Chaotic Evil",
    photo: badger,
    photographer: "Vincent van Zalinge",
    link: "https://unsplash.com/@vincentvanzalinge",
  },
  {
    name: "Baboon",
    aka: "Red butt",
    cool: 8,
    largeness: 5,
    handsome: 8,
    alignment: "Chaotic Neutral",
    photo: baboon,
    photographer: "Max van den Oetelaar",
    link: "https://unsplash.com/@maxvdo",
  },
  {
    name: "Kangaroo",
    aka: "Skippy",
    cool: 8,
    largeness: 7,
    handsome: 8,
    alignment: "Neutral Good",
    photo: kangaroo,
    photographer: "Mark Stoop",
    link: "https://unsplash.com/@markstoop",
  },
  {
    name: "Ladybird",
    aka: "Spotty",
    cool: 3,
    largeness: 1,
    handsome: 10,
    alignment: "Chaotic Good",
    photo: ladybird,
    photographer: "Vincent van Zalinge",
    link: "https://unsplash.com/@vincentvanzalinge",
  },
  {
    name: "Monkey",
    aka: "Cheeky",
    cool: 9,
    largeness: 4,
    handsome: 7,
    alignment: "Chaotic Good",
    photo: monkey,
    photographer: "Jamie Haughton",
    link: "https://unsplash.com/@haughters",
  },
  {
    name: "Stag Beetle",
    aka: "Small fry",
    cool: 7,
    largeness: 1,
    handsome: 5,
    alignment: "Neutral Evil",
    photo: stagbeetle,
    photographer: "Krzysztof Niewolny",
    link: "https://unsplash.com/@epan5",
  },
  {
    name: "T-Rex",
    aka: "Big trouble",
    cool: 10,
    largeness: 10,
    handsome: 5,
    alignment: "Chaotic Neutral",
    photo: trex,
    photographer: "Umanoide",
    link: "https://unsplash.com/@umanoide",
  },
];

export { cards };
